version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "09:00"
      timezone: America/Toronto
    open-pull-requests-limit: 5
    groups:
      npm-minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      npm-security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:15"
      timezone: America/Toronto
    open-pull-requests-limit: 5
    groups:
      github-actions-minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      github-actions-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
